import { ArrowRight, Check, Languages, Leaf, LockKeyhole, MapPin, Smartphone, UserRound } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import { languages } from '../i18n'
import { Button } from '../components/UI'

const AuthFrame=({children,title,subtitle})=><main className="auth-page"><aside className="auth-story"><Link to="/" className="brand"><div className="brand-mark"><Leaf/></div><div><strong>Krishiniti</strong><span>Smart Crop Advisory</span></div></Link><div><p className="eyebrow">FIELD TO FUTURE</p><h1>Better farm decisions begin with better context.</h1><p>Combine your soil, field, weather and market estimates into one practical crop plan.</p></div><small>Designed for clear, responsible agricultural guidance.</small></aside><section className="auth-panel"><div className="auth-card"><h2>{title}</h2><p>{subtitle}</p>{children}</div></section></main>

export function Login(){const {login}=useApp();const nav=useNavigate();const [form,setForm]=useState({mobile:'9999999999',password:'demo123'});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');try{await login(form.mobile,form.password);nav('/dashboard')}catch(err){setError(err.message)}finally{setBusy(false)}};return <AuthFrame title="Welcome back" subtitle="Sign in to see what your fields need today."><form onSubmit={submit} className="form-stack"><label>Mobile number<div className="input-wrap"><Smartphone/><input value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} inputMode="numeric" required/></div></label><label>Password<div className="input-wrap"><LockKeyhole/><input value={form.password} onChange={e=>setForm({...form,password:e.target.value})} type="password" required/></div></label>{error&&<p className="form-error">{error}</p>}<Button loading={busy} className="full">Sign in <ArrowRight size={17}/></Button></form><div className="demo-box"><span>Demo account</span><p>Mobile: 9999999999 &nbsp; · &nbsp; Password: demo123</p><button onClick={()=>setForm({mobile:'9999999999',password:'demo123'})}>Use demo credentials</button></div><p className="auth-switch">New to Krishiniti? <Link to="/register">Create an account</Link></p></AuthFrame>}

export function Register(){const {register}=useApp();const nav=useNavigate();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [form,setForm]=useState({name:'',mobile:'',password:'',location:'Ahmedabad, Gujarat',farm_size:2,preferred_language:'en'});const change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');try{await register({...form,farm_size:+form.farm_size});nav('/language')}catch(err){setError(err.message)}finally{setBusy(false)}};return <AuthFrame title="Create your farmer profile" subtitle="It takes about a minute. You can change these details later."><form onSubmit={submit} className="form-grid"><label>Full name<div className="input-wrap"><UserRound/><input name="name" value={form.name} onChange={change} required placeholder="Ramesh Patel"/></div></label><label>Mobile number<div className="input-wrap"><Smartphone/><input name="mobile" value={form.mobile} onChange={change} required inputMode="numeric"/></div></label><label>Location<div className="input-wrap"><MapPin/><input name="location" value={form.location} onChange={change} required/></div></label><label>Farm size (acres)<input name="farm_size" value={form.farm_size} onChange={change} min="0" step="0.1" type="number"/></label><label className="span-two">Create password<div className="input-wrap"><LockKeyhole/><input name="password" value={form.password} onChange={change} minLength="6" required type="password"/></div></label>{error&&<p className="form-error span-two">{error}</p>}<Button loading={busy} className="full span-two">Create account <ArrowRight size={17}/></Button></form><p className="auth-switch">Already registered? <Link to="/login">Sign in</Link></p></AuthFrame>}

export function Language(){const {language,setLanguage,t}=useApp();const nav=useNavigate();return <main className="language-page"><div className="language-card"><div className="language-icon"><Languages/></div><p className="eyebrow">YOUR LANGUAGE</p><h1>Choose the language that feels natural</h1><p>Navigation and important farm guidance will use your selection.</p><div className="language-grid">{languages.map(item=><button key={item.code} className={language===item.code?'selected':''} onClick={()=>setLanguage(item.code)}><span>{item.native}</span><small>{item.label}</small>{language===item.code&&<Check/>}</button>)}</div><Button className="full" onClick={()=>nav('/dashboard')}>{t('continue')} <ArrowRight size={17}/></Button></div></main>}
