import { ArrowRight, CloudRain, CloudSun, Droplets, HeartPulse, IndianRupee, MapPin, Sprout, TrendingDown } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Area, AreaChart, ResponsiveContainer } from 'recharts'
import { useApp } from '../context/AppContext'
import { api, demoHistory } from '../services/api'
import { Badge, Loading, Metric } from '../components/UI'

export default function Dashboard(){const {t}=useApp();const [data,setData]=useState(null);useEffect(()=>{api.dashboard().then(setData)},[]);if(!data)return <Loading/>;if(data.empty)return <div className="empty-state-page"><Sprout/><h1>Your farm journey starts here</h1><p>Add your first farm and draw a field boundary to unlock recommendations.</p><Link className="button button-primary" to="/farms">Create a farm</Link></div>;const d=data;return <>
  <div className="dashboard-head"><div><p className="eyebrow">{new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</p><h1>{t('goodAfternoon')}, {d.farmer?.split(' ')[0]}</h1><p>{t('attention')}</p></div><Badge tone="sand">{t('dataNote')}</Badge></div>
  <section className="priority-card"><div className="priority-copy"><div className="priority-label"><Droplets size={16}/>{t('todayPriority')}</div><h2>{d.today_advisory?.code==='DELAY_IRRIGATION'?'Wait before irrigating '+(d.field.current_crop||'your crop'):d.today_advisory?.message}</h2><p>{d.today_advisory?.message}</p><Link className="button button-light" to="/advisories">{t('viewAdvisory')} <ArrowRight size={17}/></Link></div><div className="rain-gauge"><CloudRain/><strong>{d.weather.rainfall} mm</strong><span>{d.weather.rain_probability}% rain chance</span><div><i style={{height:`${d.weather.rain_probability}%`}}/></div></div></section>
  <section className="metrics-grid"><Metric icon={HeartPulse} label={t('vegetationCondition')} value={d.ndvi.label?.replace(' vegetation','')} detail={`NDVI ${d.ndvi.current} · ${d.ndvi.trend>0?'+':''}${d.ndvi.trend}`} tone="green"/><Metric icon={Droplets} label={t('soilMoisture')} value={`${d.field.soil_moisture}%`} detail="Monitor after rainfall" tone="blue"/><Metric icon={CloudSun} label={t('weather')} value={`${d.weather.temperature}°C`} detail={d.weather.forecast_summary} tone="amber"/><Metric icon={IndianRupee} label={t('estimatedProfit')} value="₹65,328" detail="Cotton · 2.4 acres" tone="violet"/></section>
  <div className="dashboard-columns"><section className="panel field-panel"><div className="panel-head"><div><p className="eyebrow">{t('myField')}</p><h2>{d.field.name}</h2></div><Badge>{t('active')}</Badge></div><div className="field-visual"><div className="field-shape"><span>NDVI<br/><strong>{d.ndvi.current}</strong></span></div><span className="field-pin"><MapPin size={15}/> Ahmedabad</span></div><div className="field-meta"><div><span>Crop</span><strong>{d.field.current_crop||'Not selected'}</strong></div><div><span>Area</span><strong>{d.field.area} acres</strong></div><div><span>Sown</span><strong>64 days ago</strong></div></div><Link className="panel-link" to={`/fields/${d.field.id}`}>{t('openField')} <ArrowRight size={16}/></Link></section>
  <section className="panel trend-panel"><div className="panel-head"><div><p className="eyebrow">12-WEEK VIEW</p><h2>Vegetation trend</h2></div><span className="trend-down"><TrendingDown size={15}/> -0.02</span></div><div className="mini-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={demoHistory}><defs><linearGradient id="ndviMini" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3d8b5d" stopOpacity=".32"/><stop offset="100%" stopColor="#3d8b5d" stopOpacity="0"/></linearGradient></defs><Area type="monotone" dataKey="average_ndvi" stroke="#2e7d50" strokeWidth={3} fill="url(#ndviMini)"/></AreaChart></ResponsiveContainer></div><div className="insight-row"><div className="insight-icon"><Sprout/></div><p><strong>Healthy vegetation</strong><span>Small change from the previous reading. Continue field checks.</span></p></div><Link className="panel-link" to="/ndvi">View crop health <ArrowRight size={16}/></Link></section></div>
</>}
