import { ArrowRight, MapPin, Plus, Ruler, Sprout } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Button, Empty, Loading, PageHeader } from '../components/UI'
import { api } from '../services/api'

export function Farms(){const [farms,setFarms]=useState(null);const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [form,setForm]=useState({name:'',location:'Ahmedabad, Gujarat',total_area:0,latitude:22.9808,longitude:72.469});useEffect(()=>{api.farms().then(setFarms)},[]);const submit=async(e)=>{e.preventDefault();setBusy(true);const item=await api.createFarm({...form,total_area:+form.total_area,latitude:+form.latitude,longitude:+form.longitude});setFarms([...farms,item]);setShow(false);setBusy(false)};if(!farms)return <Loading/>;return <><PageHeader eyebrow="FARM MANAGEMENT" title="Your farms" description="Keep fields, soil details and crop activity organized in one place." action={<Button onClick={()=>setShow(!show)}><Plus size={17}/> Add farm</Button>}/>{show&&<form className="panel inline-form" onSubmit={submit}><h2>Add a farm</h2><label>Farm name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Green Valley Farm"/></label><label>Location<input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Approx. area (acres)<input type="number" min="0" step=".1" value={form.total_area} onChange={e=>setForm({...form,total_area:e.target.value})}/></label><Button loading={busy}>Save farm</Button></form>}{farms.length===0?<Empty title="No farms yet" text="Add a farm before drawing your first field."/>:<div className="farm-grid">{farms.map(farm=><Link to={`/farms/${farm.id}`} className="farm-card" key={farm.id}><div className="farm-art"><div/></div><div className="farm-card-copy"><div><span className="eyebrow">FARM</span><h2>{farm.name}</h2><p><MapPin size={15}/>{farm.location}</p></div><ArrowRight/></div><div className="farm-stats"><span><Ruler/> {farm.total_area||'—'} acres</span><span><Sprout/> Open fields</span></div></Link>)}</div>}</>}

export function FarmDetail(){const {id}=useParams();const [farm,setFarm]=useState(null);const [fields,setFields]=useState(null);useEffect(()=>{Promise.all([api.farm(id),api.fields(id)]).then(([a,b])=>{setFarm(a);setFields(b)})},[id]);if(!farm||!fields)return <Loading/>;return <><PageHeader back="/farms" eyebrow="FARM DETAILS" title={farm.name} description={`${farm.location} · ${farm.total_area} acres`} action={<Link className="button button-primary" to={`/fields/new?farm=${id}`}><Plus size={17}/> Draw a field</Link>}/><div className="panel map-overview"><div className="field-shape large"/><div><p className="eyebrow">LOCATION</p><h2>{farm.location}</h2><p>Farm centre: {farm.latitude}, {farm.longitude}</p><small>Map boundaries are stored for each field, not inferred from an image.</small></div></div><h2 className="section-title">Fields</h2><div className="field-list">{fields.map(field=><Link to={`/fields/${field.id}`} key={field.id} className="field-row"><div className="crop-icon"><Sprout/></div><div><h3>{field.name}</h3><p>{field.current_crop||'No crop selected'} · {field.area} acres</p></div><span>Soil moisture {field.soil?.moisture}%</span><ArrowRight/></Link>)}</div></>}
