import { Beaker, CheckCircle2, MapPinned, Sprout } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import FieldMap from '../components/FieldMap'
import { Button, Loading, PageHeader } from '../components/UI'
import { useApp } from '../context/AppContext'
import { api, demoField } from '../services/api'

const demoSoil={nitrogen:75,phosphorus:42,potassium:55,ph:6.8,soil_type:'Loamy',moisture:38}
export default function FieldEditor(){
  const {t}=useApp();const {id}=useParams();const [query]=useSearchParams();const nav=useNavigate();const editing=id&&id!=='new';const [loading,setLoading]=useState(editing);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [form,setForm]=useState({farm_id:+query.get('farm')||1,name:'',polygon:[],current_crop:'',irrigation_available:true,soil:demoSoil})
  useEffect(()=>{if(editing)api.field(id).then(data=>{setForm(data);setLoading(false)}).catch(err=>{setError(err.message||t('unableLoad'));setLoading(false)})},[editing,id,t])
  if(loading)return <Loading/>
  const setSoil=(key,value)=>setForm({...form,soil:{...form.soil,[key]:key==='soil_type'?value:Number(value)}});const useDemo=()=>setForm({...form,polygon:demoField.polygon,soil:demoSoil})
  const submit=async(e)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const result=editing?await api.updateField(id,form):await api.createField(form);nav(`/fields/${result.id}`,{state:{notice:t('fieldSaved')}})}catch(err){setError(err.message||t('unableLoad'))}finally{setBusy(false)}}
  return <><PageHeader back={`/farms/${form.farm_id}`} eyebrow={editing?t('farmDetails'):t('newField')} title={editing?form.name:t('drawYourField')} description={t('fieldDescription')}/>{error&&<div className="form-error" role="alert">{error}</div>}<form onSubmit={submit} className="field-editor"><section className="panel"><div className="section-head"><div className="step-number">1</div><div><h2>{t('fieldBoundary')}</h2><p>{t('drawAtLeast')}</p></div><Button type="button" variant="secondary" onClick={useDemo}>{t('useDemoField')}</Button></div><FieldMap polygon={form.polygon} onChange={polygon=>setForm({...form,polygon})}/><div className="form-grid compact"><label>{t('fieldName')}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Field One"/></label><label>{t('currentCrop')}<input value={form.current_crop||''} onChange={e=>setForm({...form,current_crop:e.target.value})} placeholder="Cotton"/></label></div>{form.polygon.length>0&&<p className="success-note"><CheckCircle2/> {t('boundaryReady')}</p>}</section><section className="panel"><div className="section-head"><div className="step-number">2</div><div><h2>{t('soilInformation')}</h2><p>{t('soilDescription')}</p></div><Button type="button" variant="secondary" onClick={()=>setForm({...form,soil:demoSoil})}><Beaker size={17}/> {t('useDemoSoil')}</Button></div><div className="soil-grid">{[['nitrogen','nitrogen'],['phosphorus','phosphorus'],['potassium','potassium'],['ph','soilPh'],['moisture','moisture']].map(([key,label])=><label key={key}>{t(label)}<input type="number" step=".1" min="0" value={form.soil?.[key]??''} onChange={e=>setSoil(key,e.target.value)} required/></label>)}<label>{t('soilType')}<select value={form.soil?.soil_type||'Loamy'} onChange={e=>setSoil('soil_type',e.target.value)}>{['Loamy','Black','Clay','Sandy'].map(value=><option key={value}>{value}</option>)}</select></label></div><label className="check-row"><input type="checkbox" checked={form.irrigation_available} onChange={e=>setForm({...form,irrigation_available:e.target.checked})}/><span><strong>{t('irrigationAvailable')}</strong><small>{t('irrigationNote')}</small></span></label></section><div className="sticky-action"><div><MapPinned/><span>{form.polygon.length>0?t('boundaryAndSoilReady'):t('drawBoundary')}</span></div><Button loading={busy} disabled={form.polygon.length<4}><Sprout size={17}/>{editing?t('saveField'):t('createField')}</Button></div></form></>
}
