import { AlertTriangle, Bell, Check, ChevronRight, CloudRain, Droplets, HeartPulse, Languages, Leaf, LogOut, ShieldAlert, Sprout, Stethoscope } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api } from '../services/api'
import { Badge, Button, Loading, PageHeader } from '../components/UI'
import { useApp } from '../context/AppContext'
import { languages } from '../i18n'

export function DiseaseAdvisor(){const {t}=useApp();const [crops,setCrops]=useState(null);const [cropId,setCropId]=useState(1);const [symptoms,setSymptoms]=useState([]);const [selected,setSelected]=useState([]);const [result,setResult]=useState(null);const [busy,setBusy]=useState(false);useEffect(()=>{api.diseaseCrops().then(items=>{setCrops(items);if(items[0])setCropId(items[0].id)})},[]);useEffect(()=>{setSelected([]);setResult(null);api.symptoms(cropId).then(setSymptoms)},[cropId]);if(!crops)return <Loading/>;const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);const analyze=async()=>{setBusy(true);setResult(await api.analyzeDisease(+cropId,selected));setBusy(false)};return <><PageHeader eyebrow="SYMPTOM-BASED GUIDANCE" title="What are you noticing?" description="Select visible symptoms to find crop-specific possible issues. This does not use an image classifier." action={<Badge tone="sand">Advisory only</Badge>}/><div className="disease-layout"><section className="panel disease-form"><label>Crop<select value={cropId} onChange={e=>setCropId(+e.target.value)}>{crops.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className="symptom-head"><h2>Select all visible symptoms</h2><span>{selected.length} selected</span></div><div className="symptom-grid">{symptoms.map(s=><button type="button" className={selected.includes(s.id)?'selected':''} onClick={()=>toggle(s.id)} key={s.id}><span>{s.name}</span>{selected.includes(s.id)?<Check/>:<i/>}</button>)}</div><Button className="full" loading={busy} disabled={!selected.length} onClick={analyze}><Stethoscope size={18}/> Compare possible issues</Button></section><aside className="disease-help"><ShieldAlert/><h2>Use what you can see</h2><p>Choose symptoms from several parts of the plant where possible.</p><ol><li>Check upper and lower leaves</li><li>Look for insects or residue</li><li>Notice whether symptoms are spreading</li></ol></aside></div>{result&&<section className="diagnosis-results"><div className="diagnosis-note"><AlertTriangle/><p><strong>{t('advisoryDisclaimer')}</strong><span>{result.message}</span></p></div>{result.matches.map((match,index)=><article key={match.possible_issue} className="diagnosis-card"><div className="match-score"><strong>{match.match_confidence}%</strong><span>symptom match</span></div><div><p className="eyebrow">{index===0?'MOST LIKELY MATCH':'OTHER POSSIBLE ISSUE'}</p><h2>{match.possible_issue}</h2><p>{match.recommended_action}</p><div className="management-grid"><div><strong>Prevention</strong><span>{match.prevention}</span></div><div><strong>Management</strong><span>{match.management}</span></div></div></div><Badge tone="sand">{match.severity} severity</Badge></article>)}</section>}</>}

export function Advisories(){const [items,setItems]=useState(null);useEffect(()=>{api.advisories(1).then(setItems)},[]);if(!items)return <Loading/>;const icons={irrigation:Droplets,crop_health:HeartPulse,weather:CloudRain};return <><PageHeader eyebrow="ACTION CENTRE" title="Farm advisories" description="Prioritized guidance based on your field, weather, soil moisture and vegetation condition."/><div className="advisory-list">{items.map((item,index)=>{const Icon=icons[item.type]||Sprout;return <article key={item.id} className="advisory-row"><div className={`advisory-icon severity-${item.severity}`}><Icon/></div><div><div><span className="eyebrow">{item.type.replace('_',' ')}</span><Badge tone={item.severity==='moderate'?'sand':'green'}>{item.severity}</Badge></div><h2>{index===0?'Wait and check before irrigating':'Continue routine crop checks'}</h2><p>{item.message}</p><small>Generated from available field data · Advisory only</small></div><ChevronRight/></article>})}</div></>}

export function Notifications(){const [items,setItems]=useState(null);useEffect(()=>{api.notifications().then(setItems)},[]);if(!items)return <Loading/>;const read=async id=>{await api.readNotification(id);setItems(items.map(x=>x.id===id?{...x,is_read:true}:x))};return <><PageHeader eyebrow="UPDATES" title="Notifications" description="Weather, field health and planning updates for your farms." action={<Badge>{items.filter(x=>!x.is_read).length} unread</Badge>}/><div className="notification-list">{items.map(item=><button key={item.id} onClick={()=>read(item.id)} className={item.is_read?'read':''}><div className={`notification-icon ${item.type}`}><Bell/></div><div><span>{item.type}</span><h2>{item.title}</h2><p>{item.message}</p><small>Today</small></div>{!item.is_read&&<i/>}</button>)}</div></>}

export function SettingsPage(){const {user,language,setLanguage,logout,t}=useApp();const nav=useNavigate();return <><PageHeader eyebrow="PREFERENCES" title="Settings" description="Manage your profile, language and data mode."/><div className="settings-grid"><section className="panel profile-card"><div className="profile-avatar">{user?.name?.[0]}</div><h2>{user?.name}</h2><p>{user?.mobile}</p><span>{user?.location}</span><Button variant="danger" onClick={()=>{logout();nav('/')}}><LogOut/> {t('logout')}</Button></section><section className="panel"><div className="setting-title"><Languages/><div><h2>Language</h2><p>Applies to navigation and key advisories.</p></div></div><div className="settings-languages">{languages.map(item=><button className={language===item.code?'selected':''} onClick={()=>setLanguage(item.code)} key={item.code}><span>{item.native}</span><small>{item.label}</small>{language===item.code&&<Check/>}</button>)}</div><div className="setting-title divider"><Leaf/><div><h2>Data mode</h2><p>External services fall back automatically when credentials are missing.</p></div><Badge tone="sand">Demo mode active</Badge></div></section></div><div className="info-callout"><ShieldAlert/><p><strong>Responsible use</strong><span>Financial values are estimates. Disease matching is advisory. NDVI indicates vegetation condition and does not confirm a disease or pest.</span></p></div></>}
