import { AlertTriangle, CloudRain, CloudSun, Droplets, Gauge, HeartPulse, Info, Leaf, Navigation, Thermometer, TrendingDown, Wind } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../services/api'
import { Badge, Loading, Metric, PageHeader } from '../components/UI'

export function NDVI(){const [current,setCurrent]=useState(null);const [history,setHistory]=useState(null);useEffect(()=>{Promise.all([api.ndvi(1),api.ndviHistory(1)]).then(([a,b])=>{setCurrent(a);setHistory(b.records)})},[]);if(!current||!history)return <Loading/>;return <><PageHeader eyebrow="VEGETATION CONDITION INDICATOR" title="See how the field is changing" description="Sentinel-2 style NDVI history in demo mode. This indicates vegetation condition or stress—it does not diagnose disease." action={<Badge tone="sand">Demo Sentinel-2</Badge>}/><section className="ndvi-hero"><div className="ndvi-score"><div style={{'--score':`${current.average_ndvi*100}%`}}><Leaf/><strong>{current.average_ndvi}</strong><span>current NDVI</span></div></div><div className="ndvi-copy"><Badge>{current.interpretation.label}</Badge><h2>Vegetation remains in a healthy range</h2><p>{current.interpretation.message}</p><div className="ndvi-comparison"><span>Previous<strong>{current.previous_ndvi}</strong></span><TrendingDown/><span>Change<strong>{current.trend}</strong></span><span>Cloud cover<strong>{current.cloud_percentage||12}%</strong></span></div></div></section><section className="panel chart-panel"><div className="panel-head"><div><p className="eyebrow">HISTORICAL NDVI</p><h2>12-week field trend</h2></div><Badge tone="gray">B08 NIR · B04 Red</Badge></div><div className="ndvi-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={history} margin={{left:-18,right:10,top:20}}><defs><linearGradient id="ndviArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#3f8d5f" stopOpacity=".35"/><stop offset="1" stopColor="#3f8d5f" stopOpacity=".02"/></linearGradient></defs><CartesianGrid stroke="#e5eadf" vertical={false}/><XAxis dataKey="observation_date" tickFormatter={v=>v.slice(5)} tickLine={false} axisLine={false}/><YAxis domain={[0,1]} tickLine={false} axisLine={false}/><Tooltip/><Area type="monotone" dataKey="average_ndvi" stroke="#2c7a4d" strokeWidth={3} fill="url(#ndviArea)" dot={{r:4,fill:'#fff',stroke:'#2c7a4d',strokeWidth:2}}/></AreaChart></ResponsiveContainer></div><div className="threshold-row"><span><i className="t-healthy"/> &gt;0.65 Healthy</span><span><i className="t-good"/> 0.45–0.65 Moderate/good</span><span><i className="t-watch"/> 0.25–0.45 Potential stress</span><span><i className="t-low"/> &lt;0.25 Low signal</span></div></section><div className="info-callout"><Info/><p><strong>Read NDVI with field context</strong><span>Clouds, crop stage, bare soil and recent irrigation can affect readings. Confirm concerns with weather, soil moisture and visible symptoms.</span></p></div></>}

export function Weather(){const [data,setData]=useState(null);useEffect(()=>{api.weather(1).then(setData)},[]);if(!data)return <Loading/>;return <><PageHeader eyebrow="FIELD WEATHER" title="Plan around the next conditions" description="Weather falls back to realistic demo values whenever live credentials are unavailable." action={<Badge tone="sand">{data.provider==='demo'?'Demo provider':'Live provider'}</Badge>}/><section className="weather-hero"><div><div className="weather-place"><Navigation/> Field One · Ahmedabad</div><div className="temperature"><CloudSun/><strong>{data.temperature}°</strong><span>{data.forecast_summary}</span></div></div><div className="rain-window"><CloudRain/><span>Rain forecast</span><strong>{data.rainfall} mm</strong><p>{data.rain_probability}% probability</p></div></section><section className="metrics-grid three"><Metric icon={Droplets} label="Humidity" value={`${data.humidity}%`} detail="Moderately humid" tone="blue"/><Metric icon={Wind} label="Wind" value={`${data.wind_speed} km/h`} detail="Light breeze" tone="green"/><Metric icon={Gauge} label="Weather risk" value={data.weather_risk} detail="Watch rainfall timing" tone="amber"/></section><section className="panel advisory-detail"><div className="advisory-symbol"><Droplets/></div><div><p className="eyebrow">IRRIGATION ADVISORY</p><h2>{data.irrigation_advisory.code==='DELAY_IRRIGATION'?'Consider waiting before irrigation':'Monitor irrigation need'}</h2><p>{data.irrigation_advisory.localized_message||data.irrigation_advisory.message}</p><small>Advisory only. Check your field before taking action.</small></div></section><div className="hourly-strip">{[['Now','31°',CloudSun],['3 PM','32°',CloudSun],['6 PM','29°',CloudRain],['9 PM','27°',CloudRain],['Tomorrow','30°',CloudSun]].map(([time,temp,Icon])=><div key={time}><span>{time}</span><Icon/><strong>{temp}</strong></div>)}</div></>}
