import { ArrowRight, ChartNoAxesCombined, CloudSun, HeartPulse, Leaf, MapPinned, ShieldCheck, Sprout } from 'lucide-react'
import { Link } from 'react-router-dom'

export default function Welcome(){return <main className="welcome-page">
  <header className="welcome-nav"><div className="brand"><div className="brand-mark"><Leaf size={21}/></div><div><strong>Krishiniti</strong><span>Smart Crop Advisory</span></div></div><div><Link className="text-link" to="/login">Sign in</Link><Link className="button button-primary" to="/register">Get started</Link></div></header>
  <section className="hero"><div className="hero-copy"><span className="hero-kicker"><Sprout size={16}/> Built for small and marginal farmers</span><h1>Know what to grow.<br/><em>Grow with confidence.</em></h1><p>One clear place to choose a suitable crop, understand estimated profit, monitor field health and decide what needs attention today.</p><div className="hero-actions"><Link className="button button-primary button-large" to="/login">Explore demo <ArrowRight size={18}/></Link><a className="button button-secondary button-large" href="#how">See how it works</a></div><div className="trust-row"><ShieldCheck size={18}/><span>Works without paid API keys</span><i/> <span>Advisory, not guesswork</span></div></div>
  <div className="hero-visual"><div className="field-orbit orbit-one"/><div className="field-orbit orbit-two"/><div className="phone-card"><div className="phone-head"><div><small>GOOD AFTERNOON</small><strong>Demo Farmer</strong></div><div className="sun-chip"><CloudSun size={19}/>31°</div></div><div className="priority-mini"><span>TODAY'S PRIORITY</span><strong>Wait before irrigating cotton</strong><p>Rain is likely this evening.</p></div><div className="mini-grid"><div><HeartPulse/><strong>0.67</strong><small>NDVI · Good</small></div><div><ChartNoAxesCombined/><strong>₹65k</strong><small>Est. profit</small></div></div></div><div className="float-card crop-float"><span>Best crop match</span><strong>Cotton · 91%</strong></div><div className="float-card map-float"><MapPinned/><div><strong>2.4 acres</strong><span>Field One</span></div></div></div></section>
  <section id="how" className="feature-strip">{[[Sprout,'Choose the right crop','Soil, season, weather and water are scored together.'],[ChartNoAxesCombined,'Plan for profit','Compare yield, cost, revenue and risk-adjusted profit.'],[HeartPulse,'Watch field health','Track vegetation condition, weather and irrigation guidance.']].map(([Icon,title,text])=><article key={title}><div><Icon/></div><h2>{title}</h2><p>{text}</p></article>)}</section>
  <footer className="welcome-foot"><p>Financial figures are estimates. Crop concern results are advisory only. NDVI indicates vegetation condition and does not confirm disease.</p></footer>
</main>}
